### ISSUE TITLE
Marketing Dashboard

### ISSUE THREAD

**Issue by brianlagunas** [Infragistics/angular-samples#3]
Recreate this dashboard in Angular:

http://igniteui.com/marketing-dashboard-sample#_ga=2.73085520.279104778.1563990366-1434096526.1554741326

**Comment by StefanIvanov** [comment]
can we add @desig9stein as an assignee here, he will be able to help within the sprint that starts today

**Comment by brianlagunas** [comment]
@StefanIvanov done

**Comment by brianlagunas** [comment]
The repo for this sample can be found here:

https://github.com/IgniteUI/marketing-dashboard

**Comment by zdrawku** [comment]
Brian, I am closing this issue, now that the app is available on its own repository. We are going to add both "[localization](https://github.com/IgniteUI/igniteui-angular-marketing-dashboard/issues/6)" and "[responsive design](https://github.com/IgniteUI/igniteui-angular-marketing-dashboard/issues/3)" tasks in it and keep track of them.

As for the application samples page for the marketing dashboard, next sprint we are going to host the application and make a request to be added under [application samples](https://www.infragistics.com/resources/sample-applications) angular page.
